name: Test Python application and Build & Push docker image to github package and dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r req.txt
    - name: Test with pytest
      run: |
        pytest test.py --doctest-modules --junitxml=junit/test-results.xml
        ls -ltr

    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: junit/test-results.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    
    - name: Run tests with coverage
      run: |
          coverage run -m pytest test.py
          coverage xml -o coverage.xml
          coverage report -m
      working-directory: /home/runner/work/batchfivecicd/batchfivecicd

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
          name: coverage-report
          path: coverage.xml
    - name: Build PyInstaller executable
      run: |
          pip install pyinstaller
          pyinstaller --onefile app.py
      working-directory: /home/runner/work/batchfivecicd/batchfivecicd

    - name: Upload executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/
