name: Test Python application and Build & Push docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r req.txt
    - name: Test with pytest
      run: |
        pytest test.py

  build-and-push-docker-image-to-github-packages:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with: 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/sampleapp
        tag_with_sha: true
        tag_with_ref: true
  
  # build-and-push-docker-image-to-dockerhub:
  #   runs-on: ubuntu-latest   
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #           username: ${{ secrets.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
  #     - name: Run Docker container
  #       run: docker run hello-world
  #     - name: Push to docker Hub
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         repository: psrv3/gatest
  #         tag_with_ref: true
